### ISSUE TITLE
Add a Dockerfile

### ISSUE THREAD

**Issue by goRaspy** [kima-ventures/reporting#1]
Super projet, qui semble intéressant pour structurer la relation entre investisseurs et start-up.

Néanmoins, un petit dockerfile faciliterait la vie de ceux qui veulent se passer d'Heroku :)

**Comment by alexisrobert** [comment]
Si tu veux te passer d'Heroku tu peux utiliser https://github.com/dokku/dokku – c'est ce qu'on utilise chez Kima :)

Mais c'est vrai qu'un Dockerfile pourrait être intéressant :)
